site_name: Peter's home
# site_url: https://peter5723.github.io/
# nav快速添加导航栏




theme:
  name: 'material'
  palette:
    primary: custom
    accent: custom
  icon:
    repo: fontawesome/solid/trash
  features:
    - content.code.copy
    #- navigation.tracking #地址栏中的 URL 将自动更新为在目录中突出显示的活动锚点
    #- navigation.tabs #顶级部分将呈现在上面视口标题下方的菜单层中，但在移动设备上保持原样
    # - navigation.tabs.sticky  #启用粘性选项卡后，导航选项卡将锁定在标题下方，并在向下滚动时始终保持可见
    #- navigation.sections #启用部分后，顶级部分在边栏中呈现为1220px以上视口的组，但在移动设备上保持原样
    #- navigation.top # 返回顶部的按钮 在上滑时出现
    #- navigation.footer #页脚将呈现在边栏中，但在移动设备上保持原样
    - search.suggest # 搜索输入一些字母时推荐补全整个单词
    - search.highlight # 搜索出的文章关键词加入高亮
    - search.share #搜索分享按钮
    #- navigation.expand # 打开Tab时左侧目录全部展开
    #- navigation.indexes #启用节索引页后，可以将文档直接附加到节
  font:
    text: Noto Serif SC
    code: Roboto Mono
    # code:
    #   - Inconsolata


markdown_extensions:
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight:                     # 代码高亮
      #auto_title: true
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.betterem
  - pymdownx.caret
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.critic
  - pymdownx.details
  - toc:
      permalink: true                         # 每个标题后面的 锚链接
      #toc_depth: 2                           # table of content 显示的级数，0就不会显示
  - footnotes
  - meta
  - attr_list
  - md_in_html

extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

plugins:
  - search:
      lang: ja                               # 实测搜索语言改成日本可以支持中文搜搜
  - git-revision-date-localized:
      type: iso_date
      custom_format: "%d. %B %Y"
      timezone: Asia/Shanghai
      locale: en
      fallback_to_build_date: false
      enable_creation_date: true
      exclude:
          - index.md
      enabled: true
      strict: true

extra_css:
  - stylesheets/riscv.css
  - stylesheets/extra.css
  # - https://cdn.jsdelivr.net/npm/lxgw-wenkai-webfont@1.1.0/style.css  #字体

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/peter5723/peter5723.github.io

nav:
  - Home: index.md
  - About: about.md
  - "build a website":
    - "mkdocs": "website/mkdocs.md"
    - "jekyll": "website/github-pages.md"
    - "图床": "website/pic-bed.md"
  - "工具":
    - "vscode": "tools/vscode.md"
    - "shell": "tools/shell.md"
    - "vim": "tools/vim.md"
    - "git": "tools/git.md"
    - "GNU Make": "tools/make.md"
    - "cmake": "tools/cmake.md"
    - "网络": "tools/ssh.md"
  - "化学":
    - "化学热力学中的一些问题": "chem/thermo.md"
  - "信号":
    - "z变换": "signal/onesidez.md"
    - "DFT": "signal/DFT.md"
    - "短时傅里叶变换": "signal/stft.md"
    - "LTI系统频域特性（ss第6章）": "signal/ch6_ss.md"
    - "PCA 法滤波": "signal/pca.md"
  - "计算机系统":
    - "PA 实验记录": "ICS/2023-11-02-PAnote.md"
    - "RISC-V": "ICS/riscv.md"
    - "数字与算术": "ICS/number.md"
    - "链接和程序结构": "ICS/links.md"
    - "栈和函数调用": "ICS/stack.md"
    - "基本存储": "ICS/memory.md"
    - "虚拟内存": "ICS/vm.md"
    - "IO 和文件系统": "ICS/io.md"
    - "回调函数": "ICS/callback.md"
  - "操作系统":
    - "os 实验记录": "os/osnote.md"
    - "线程": "os/thread.md"
    - "xv6 源代码": "os/src.md"
  - "算法":
    - "介绍": "algorithm/intro.md"
    - "搜索":
      - "DFS": "algorithm/search/DFS.md"
    - "动态规划": "algorithm/dp.md"
  - "C++":
    - "CS106L 笔记": "Cpp/intro.md"
  - "书":
    - "鼠疫": "wen/LaPeste.md"
    - "西西弗神话": "wen/sisyphe.md"
    - "局外人": "wen/outsider.md"
    - "卡拉马佐夫兄弟": "wen/kab.md"
    - "赌徒": "wen/beggar.md"
    - "Dubliners": "wen/Dubliners.md"
  - diary:
    - "one diary":
      - "one one diary": "diary.md"
