site_name: Peter's home
# site_url: https://peter5723.github.io/
# nav快速添加导航栏




theme: 
  name: 'material'
  palette:
    primary: custom
    accent: custom
  icon:
    repo: fontawesome/solid/trash
  features:
    - content.code.copy
    #- navigation.tracking #地址栏中的 URL 将自动更新为在目录中突出显示的活动锚点
    #- navigation.tabs #顶级部分将呈现在上面视口标题下方的菜单层中，但在移动设备上保持原样
    # - navigation.tabs.sticky  #启用粘性选项卡后，导航选项卡将锁定在标题下方，并在向下滚动时始终保持可见
    #- navigation.sections #启用部分后，顶级部分在边栏中呈现为1220px以上视口的组，但在移动设备上保持原样
    #- navigation.top # 返回顶部的按钮 在上滑时出现
    #- navigation.footer #页脚将呈现在边栏中，但在移动设备上保持原样
    - search.suggest # 搜索输入一些字母时推荐补全整个单词
    - search.highlight # 搜索出的文章关键词加入高亮
    - search.share #搜索分享按钮
    #- navigation.expand # 打开Tab时左侧目录全部展开
    #- navigation.indexes #启用节索引页后，可以将文档直接附加到节
  font:
    code:
      - Inconsolata


markdown_extensions:
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.highlight:                     # 代码高亮
      #auto_title: true
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.betterem
  - pymdownx.caret
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.critic
  - pymdownx.details
  - toc:
      permalink: true                         # 每个标题后面的 锚链接
      #toc_depth: 2                           # table of content 显示的级数，0就不会显示
  - footnotes
  - meta

extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

plugins:
  - search:
      lang: ja                               # 实测搜索语言改成日本可以支持中文搜搜
  - git-revision-date-localized:
      type: iso_date
      custom_format: "%d. %B %Y"
      timezone: Asia/Shanghai
      locale: en
      fallback_to_build_date: false
      enable_creation_date: true
      exclude:
          - index.md
      enabled: true
      strict: true

extra_css:
  - stylesheets/riscv.css
  - stylesheets/extra.css
  - https://cdn.jsdelivr.net/npm/lxgw-wenkai-webfont@1.1.0/style.css  #字体

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/peter5723/peter5723.github.io

nav:
  - Home: index.md
  - About: about.md
  - "build a website": 
    - "mkdocs": "website/mkdocs.md"
    - "jekyll": "website/github-pages.md"
  - "化学":
    - "化学热力学中的一些问题": "chem/thermo.md"
  - "信号": 
    - "单边z变换": "signal/2023-11-04-oneside_z_transform.md"
    - "DFT": "signal/DFT.md"
    - "短时傅里叶变换": "signal/stft.md"
    - "LTI系统频域特性（ss第6章）": "signal/ch6_ss.md"
  - "计算机系统": 
    - "PA 实验记录": "ICS/2023-11-02-PAnote.md"
    - "shell": "ICS/shell.md"
    - "vim": "ICS/vim.md"
    - "GNU Make": "ICS/make.md"
    - "RISC-V": "ICS/riscv.md"
    - "数字与算术": "ICS/number.md"
  - "算法":
    - "介绍": "algorithm/intro.md"
    - "搜索":
      - "DFS": "algorithm/search/DFS.md"
  - diary:
    - "one diary":
      - "one one diary": "diary.md"